# Generated by Django 5.2.7 on 2025-12-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Leave blank for specific date', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='For one-time availability/blackout', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to block this time slot')),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Booking Availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours (e.g., 2.5)', max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price for this service', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('location', models.CharField(blank=True, help_text='Shoot location or meeting place', max_length=500)),
                ('message', models.TextField(blank=True, help_text='Additional details or requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingservice')),
            ],
            options={
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['booking_date', 'booking_time'], name='booking_boo_booking_e0ff63_idx'), models.Index(fields=['status'], name='booking_boo_status_e01616_idx'), models.Index(fields=['customer_email'], name='booking_boo_custome_2675e6_idx')],
            },
        ),
    ]
