# Generated by Django 5.2.7 on 2025-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_thumbnail_url_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description for search engines', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (leave blank to use project title)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., commercial, music video, drone)', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this project has been viewed'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured', '-year'], name='portfolio_p_feature_524c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-view_count'], name='portfolio_p_view_co_a8edaa_idx'),
        ),
    ]
