# Generated by Django 5.2.7 on 2025-12-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_meta_description_project_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Lucide icon name (e.g., Video, Film, Palette)', max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='awards/')),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='portfolio.project')),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_title', models.CharField(blank=True, help_text='e.g., CEO at Company', max_length=200)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('client_photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('client_photo_url', models.URLField(blank=True, help_text='External image URL')),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
